name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Install Ansible
      run: sudo apt-get install ansible

    - name: Run Ansible Playbook
      run: ansible-playbook playbook.yml -e kubeconfig=./kubeconfig

    - name: Deploy ArgoCD
      run: kubectl apply -f kubernetes/argocd.yaml

    - name: Deploy "App of Apps" Application
      run: kubectl apply -f applications/app-of-apps.yaml
